# Generated by Django 3.2.9 on 2021-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('api_key', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('api_secret', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
            ],
        ),
    ]
